# Generated by Django 2.2.17 on 2020-12-20 19:32

from django.db import migrations, models
import utilities.files


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=utilities.files.get_file_path),
        ),
    ]
