# Generated by Django 2.2.17 on 2021-01-17 20:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('authapp', '0002_auto_20210117_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activate_key',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Код активации'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 20, 50, 35, 600051, tzinfo=utc)),
        ),
    ]
