# Generated by Django 2.2.17 on 2021-01-18 18:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210117_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 18, 43, 42, 910617, tzinfo=utc)),
        ),
    ]
