# Generated by Django 3.1.5 on 2021-01-30 21:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('authapp', '0007_auto_20210127_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activate_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 1, 21, 12, 56, 233502, tzinfo=utc)),
        ),
    ]
